import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'react-hot-toast';
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={`${inter.variable} antialiased`}>
          <Header />
          {children}
          <Footer />
          <Toaster 
            position="bottom-right" 
            toastOptions={{
              style: {
                background: '#000000',
                color: '#ffffff'
              }
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}